import mongoose from "mongoose";
import {
  EmployeeTypes,
  LoanApplicationSteps,
  LoanTypes,
  ResidenceTypes,
} from "./loan.config.js";

const loanModel = new mongoose.Schema(
  {
    applicationNumber: String,
    name: String,
    fatherName: String,
    motherName: String,
    mobile: String,
    email: String,
    dob: Date,
    resisdentLand: {
      type: String,
      enum: ResidenceTypes,
    },
    loanAmount: Number,
    loanType: { type: Array },
    monthlyIncome: Number,
    loanTenure: Number,
    interestRate: Number,
    status: {
      type: String,
      enum: LoanApplicationSteps,
      default: "application_number_generated",
    },
    loanRejectedReason: String,
    createdBy: mongoose.Schema.Types.ObjectId,
    addressVerifiedBy: mongoose.Schema.Types.ObjectId,
    officeOrBussinessVerifiedBy: mongoose.Schema.Types.ObjectId,
    documentVerifiedBy: mongoose.Schema.Types.ObjectId,
    loanVerifiedBy: mongoose.Schema.Types.ObjectId,
    branch: mongoose.Schema.Types.ObjectId,
    loanAllotAgent: mongoose.Schema.Types.ObjectId,
    applicationStaus: {
      type: String,
      enum: ["new", "in_progress", "approved", "rejected"],
    },
    employeeType: { type: String, trim: true, enum: EmployeeTypes },
    resisdentAddress: { type: String },
    resisdentState: Number,
    resisdentCountry: Number,
    resisdentCity: Number,
    resisdentPincode: { type: String, trim: true },
    communicationAddress: { type: String },
    communicationState: Number,
    communicationCountry: Number,
    communicationCity: Number,
    communicationPincode: { type: String, trim: true },
    officeAddress: { type: String },
    officeState: Number,
    officeCountry: Number,
    officeCity: Number,
    officePincode: { type: String, trim: true },
    bussinessAddress: { type: String },
    bussinessState: Number,
    bussinessCountry: Number,
    bussinessCity: Number,
    bussinessPincode: { type: String, trim: true },
    companyName: { type: String },
    position: { type: String },
    startingYear: { type: String, trim: true },
    offerLetter: String,
    appointmentLetter: String,
    salarySlip: String,
    bussinessName: String,
    bussinessStartingYear: String,
    tradeLicence: String,
    bussinessLand: {
      type: String,
      enum: ResidenceTypes,
    },
    landDocument: String,
    aadharNumber: { type: String, trim: true },
    passportImage: String,
    voterImage: String,
    panImage: String,
    aadharImage: String,
    passbookImage: String,
    voterNumber: { type: String, trim: true },
    panNumber: { type: String, trim: true },
    passportNumber: { type: String, trim: true },
    bankName: { type: String, lowercase: true },
    accountNumber: { type: String, trim: true },
    bankBranchName: String,
    ifsc: { type: String, trim: true },
  },
  {
    timestamps: true,
  }
);

const Loan = mongoose.model("loan", loanModel);

export default Loan;
